[2024-12-27T23:28:44.332+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_dag.test_postgres_connection manual__2024-12-27T23:23:15.341949+00:00 [queued]>
[2024-12-27T23:28:44.348+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_dag.test_postgres_connection manual__2024-12-27T23:23:15.341949+00:00 [queued]>
[2024-12-27T23:28:44.349+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-12-27T23:28:44.367+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2024-12-27 23:23:15.341949+00:00
[2024-12-27T23:28:44.386+0000] {standard_task_runner.py:60} INFO - Started process 58 to run task
[2024-12-27T23:28:44.424+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_dag', 'test_postgres_connection', 'manual__2024-12-27T23:23:15.341949+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpyv3z8cb_']
[2024-12-27T23:28:44.440+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask test_postgres_connection
[2024-12-27T23:28:44.660+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline_dag.test_postgres_connection manual__2024-12-27T23:23:15.341949+00:00 [running]> on host 2f9f9418478b
[2024-12-27T23:28:44.875+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_dag' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-27T23:23:15.341949+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-27T23:23:15.341949+00:00'
[2024-12-27T23:28:44.878+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/data_pipeline_dag.py", line 50, in test_postgres_connection
    conn = psycopg2.connect(**postgres_config)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline_dag.py", line 54, in test_postgres_connection
    raise RuntimeError(f"Postgres connection failed: {e}")
RuntimeError: Postgres connection failed: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

[2024-12-27T23:28:44.899+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=data_pipeline_dag, task_id=test_postgres_connection, execution_date=20241227T232315, start_date=20241227T232844, end_date=20241227T232844
[2024-12-27T23:28:44.919+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task test_postgres_connection (Postgres connection failed: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
; 58)
[2024-12-27T23:28:44.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-27T23:28:44.968+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
